version: 0.2

env:
  shell: bash
  parameter-store:
    LABS_ACCOUNT_ID: "/labs/account_id"
    LIVE_ACCOUNT_ID: "/live/account_id"

phases:
  build:
    commands:
      - make ci
      - make tf-checks
      - ./scripts/plan.sh ci
      - ./scripts/plan.sh labs
      - ./scripts/plan.sh live
