plugins:
  preset-lint-consistent:
  preset-lint-markdown-style-guide:
  preset-lint-recommended:
  validate-links:
    repository: false
  # Customized settings
  lint-list-item-indent: mixed
  lint-maximum-line-length: 120
  lint-no-missing-blank-lines:
  remark-lint-ordered-list-marker-value: ordered
  remark-lint-no-missing-blank-lines: false
  remark-lint-list-item-spacing: false
  remark-lint-maximum-heading-length: 80
