# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "grant-user-access-tf-state-d0dbe915091d400bd8ee7f27f0791303"
    region         = "eu-west-2"
    key            = "ci/..tfstate"
    encrypt        = true
    kms_key_id     = "alias/s3-grant-user-access-tf-state-d0dbe915091d400bd8ee7f27f0791303"
    dynamodb_table = "grant-user-access-tf-lock-d0dbe915091d400bd8ee7f27f0791303"
    acl            = "bucket-owner-full-control"
  }
}
