# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "eu-west-2"
  default_tags {
    tags = {
      "team:product" : "infra:grant-user-access"
      "Git_Project" : "aws-grant-user-access"
      "Environment" : "live"
    }
  }
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}
